model:
  type: "xgboost"
  random_state: 42
  test_size: 0.2

xgboost_params:
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 4
  subsample: 0.8
  colsample_bytree: 0.8
  use_label_encoder: False
  eval_metric: "logloss"
